export enum DECODED_EVENT_CATEGORY {
    NFT = "NFT Transaction",
    LENDING = "Lending",
    SAFE = "SAFE",
    DEX = "DEX",
    TOKEN = "Token",
    SWAP = "Swap",
    DEFI = "DeFi",
    BRIDGE = "Bridge",
    GAMING = "Gaming",
    SOCIAL = "Social",
    STAKING = "Staking",
    OTHERS = "Others",
}

export enum DECODED_ACTION {
    SWAPPED = "Swapped",
    MULTISIG_ACTION = "MultiSig",
    APPROVAL = "Approval",
    TRANSFERRED = "Transferred",
    NATIVE_TRANSFER = "Native Token Transfer",
    RECEIVED_BRIDGE = "Received Bridge",
    ACCOUNT_ABSTRACTION = "Account Abstraction Transaction",
    SALE = "Sale",
    MINT = "Mint",
    BURN = "Burn",
    WITHDRAW = "Withdraw",
    DEPOSIT = "Deposit",
    ADD_LIQUIDITY = "Add Liquidity",
    REMOVE_LIQUIDITY = "Remove Liquidity",
    UPDATE = "Update",
    FLASHLOAN = "Flashloan",
    REPAY = "Repay",
    BORROW = "Borrow",
    LIQUIDATE = "Liquidate",
    CLAIM_REWARDS = "Claim Rewards",
    GAME_ACTION = "Game Action",
    CREATE = "Create Pool",
}
