name: Lint
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
        types: [opened, synchronize]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install dependencies
              run: yarn install
            - name: Lint
              run: yarn lint
