name: Test
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
        types: [opened, synchronize]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: 'Create env file'
            run: echo "${{ secrets.ENV_FILE }}" > .env
          - name: Install dependencies
            run: yarn install
          - name: Run tests
            run: yarn test
